name: GitHub Actions Intento1
run-name: ${{ github.actor }} is testing out GitHub Actions
on: [push]
jobs:
Explore-GitHub-Actions:
 runs-on: debian-latest
 steps:
 - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
 - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
 - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
 - name: Check out repository code
   uses: actions/checkout@v2
 - name: Check python environment
   run:
     python -m pip install pytest numpy random
 - name: Test with pytest
   run:
     pytest -sv ../../test_logistic_convergence.py
